name: Prodution

on:
  deployment:

jobs:
  production_deploy:
    name: Production deployment
    runs-on: ubuntu-20.04
    steps:
      - name: The deployment step
        shell: bash
        run: |
          echo "SUFFIX=pr-${{ github.event.number }}" >> $GITHUB_ENV
      - name: Set status to deployed
        uses: actions/github-script@v4
        with:
          # https://github.com/actions/github-script
          # https://octokit.github.io/rest.js/v18#repos-create-deployment-status
          # create this deployment:
          # gh api repos/Sybrand/playing_with_actions/deployments -f ref="some_change"
          script: |
            console.log(context.payload)
            const status = (await github.repos.createDeploymentStatus({owner: context.repo.owner, repo: context.repo.repo, deployment_id: context.payload.deployment.id, state: 'success'}))
            console.log(status)
